#pragma once

#define VAR "var"
#define IMMUTE "immute"
#define LVAR "lvar"
#define MVAR "Mvar"
#define NAME "name"
#define NAME_SPACE "name_space"
#define CURRENT_MODULE "current_module"
#define CURRENT_FUNCTION "current_function"
#define FUNCTION "function"
#define _CLASS "class"
#define CODE "code"
#define _PARAMS "params"
#define ARGS "args"
#define SCOPES "scopes"
#define DESC "description"
#define OBJ_INFO "__object_info__"
#define TYPE "type"
